name: Create Stg deploy with label
on:
  # push:
  #   branches:
  #     - release
  #     - release\d+\.\d+\.\d+
  pull_request:
    types: [labeled, synchronize]
    branches:
      - release
      - release\d+\.\d+\.\d+
jobs:
  # push:
  #   if: ${{ github.event_name == 'push' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check PR labels action step
  #       id: check_pr_labels
  #       uses: shioyang/check-pr-labels-on-push-action@v1.0.12
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         labels: '["stg-deploy"]'
  #       timeout-minutes: 5
  #     - id: deploy-to-stg
  #       if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
  #       run: |
  #         echo "result: ${{ steps.check_pr_labels.outputs.result }}"
  #         echo "event_name: ${{ github.event_name }}"
  #         echo "ref_name: ${{ github.ref_name }}"
  #         echo "sha: ${{ github.sha }}"
  pull_request:
    if: ${{ github.event_name == 'pull_request' && (github.event.label.name == 'stg-deploy' || contains(github.event.pull_request.labels.*.name, 'stg-deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "GITHUB_head_ref ${{ github.head_ref }}"
      - run: echo "GITHUB_head_sha ${{ github.event.pull_request.head.sha }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."