name: Create Stg deploy with label
on:
  push:
    branches:
      - release1.1.0
  pull_request:
    branches:
      - release1.1.0
    types: [labeled]
jobs:
  create_stg_deploy_with_label:
    name: Create or Update Stg deploy with label
    if: ${{ github.event.label.name == 'deploy-stg' || contains(github.event.pull_request.labels.*.name, 'deploy-stg') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo event info
        run: echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        run: echo "GITHUB_REF: ${{ github.ref }}"
        run: echo "GITHUB_base_ref: ${{ github.base_ref }}"
        run: echo "GITHUB_base_sha: ${{ github.event.pull_request.base.sha }}"
        run: echo "GITHUB_head_ref: ${{ github.head_ref }}"
        run: echo "GITHUB_head_sha: ${{ github.event.pull_request.head.sha }}"
          
          
          
      
      