name: Stg deploy with label
on:
  push:
  pull_request:
    types: [labeled]
jobs:
  push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
      - id: deploy-to-stg
        if: contains(steps.label-the-PR.outputs.all-labels, 'stg-deploy') 
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        run: echo "GITHUB_REF ${{ github.ref }}"
        run: echo "GITHUB_head_ref ${{ github.head_ref }}"
        run: echo "GITHUB_head_sha ${{ github.event.pull_request.head.sha }}"
        run: echo "🍏 This job's status is ${{ job.status }}."
  pull_request:
    if: ${{ github.event_name == 'pull_request' && (github.event.label.name == 'stg-deploy' || contains(github.event.pull_request.labels.*.name, 'stg-deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "GITHUB_REF ${{ github.ref }}"
      - run: echo "GITHUB_head_ref ${{ github.head_ref }}"
      - run: echo "GITHUB_head_sha ${{ github.event.pull_request.head.sha }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."


