name: Remove Stg deploy with label
on:
  pull_request:
    types: [unlabeled, closed]
    branches:
      - release\d+\.\d+\.\d+
jobs:
  pull_request:
    if: ${{(github.event.label.name == 'stg-deploy' || contains(github.event.pull_request.labels.*.name, 'stg-deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "GITHUB_base_ref ${{ github.base_ref }}"
      - run: echo "GITHUB_base_sha ${{ github.event.pull_request.base.sha }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
      